spring:
  datasource:
    url: jdbc:mysql://db:3306/todoapp
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration

